#
# This Makefile regenerates session template files and test plan files
# that are checked-in. They are checked-in (yes, we know about best practice)
# because that lowers the barrier for new users.
#
# This attempt to run executable `feditest` in your $PATH. If you'd like
# to run a different executable, such as one in a virtual environment,
# invoke this Makefile with extra parameter FEDITEST=path/to/my/feditest
#

FEDITEST=feditest
Q=
# Could set from the command-line to something like: 'Q=$(shell git branch --show-current)'

EX=examples$(Q)

default : all

all : $(EX)

$(EX) : \
  $(EX)-session-templates \
  $(EX)-constellations \
  $(EX)-testplans


########## Example session templates ##########

$(EX)-session-templates : \
  $(EX)/session-templates/webfinger-server-all.json \
  $(EX)/session-templates/fediverse-follow.json

$(EX)/session-templates/webfinger-server-all.json : \
  dirs \
  tests/webfinger/server/*.py
	$(FEDITEST) generate-session-template \
		--name 'All WebFinger server tests' \
		--filter 'webfinger\.server' \
		--out $@

$(EX)/session-templates/fediverse-follow.json : \
  dirs \
  tests/*/*/*.py
	  $(FEDITEST) generate-session-template \
		--name 'Can a Fediverse account follow another' \
		--filter 'fediverse\.follow\.leader_accepts_follow_request' \
		--out $@


##### Example constellations ##########

$(EX)-constellations : \
  $(EX)/constellations/imp-vs-saas-any.json \
  $(EX)/constellations/saas-any-vs-saas-any.json \
  $(EX)/constellations/imp-vs-mastodon-local-ubos.json \
  $(EX)/constellations/imp-vs-wordpress-local-ubos.json \
  $(EX)/constellations/mastodon-local-ubos-vs-wordpress-local-ubos.json

$(EX)/constellations/imp-vs-saas-any.json : \
  dirs \
  examples/nodes/imp.json \
  examples/nodes/saas-any.json
	$(FEDITEST) create-constellation \
		--name 'Any SaaS application' \
		--node client=examples/nodes/imp.json \
		--node server=examples/nodes/saas-any.json \
		--out $@

$(EX)/constellations/saas-any-vs-saas-any.json : \
  dirs \
  examples/nodes/saas-any.json \
  examples/nodes/saas-any.json
	$(FEDITEST) create-constellation \
		--name 'Any Saas application vs any SaaS application' \
		--node leader_node=examples/nodes/saas-any.json \
		--node follower_node=examples/nodes/saas-any.json \
		--out $@

$(EX)/constellations/imp-vs-mastodon-local-ubos.json : \
  dirs \
  examples/nodes/imp.json \
  examples/nodes/mastodon-local-ubos.json
	$(FEDITEST) create-constellation \
		--name 'Mastodon (local, UBOS)' \
		--node client=examples/nodes/imp.json \
		--node server=examples/nodes/mastodon-local-ubos.json \
		--out $@

$(EX)/constellations/imp-vs-wordpress-local-ubos.json : \
  dirs \
  examples/nodes/imp.json \
  examples/nodes/wordpress-local-ubos.json
	$(FEDITEST) create-constellation \
		--name 'WordPress + ActivityPub plugin (local, UBOS)' \
		--node client=examples/nodes/imp.json \
		--node server=examples/nodes/wordpress-local-ubos.json \
		--out $@

$(EX)/constellations/mastodon-local-ubos-vs-wordpress-local-ubos.json : \
  dirs \
  examples/nodes/mastodon-local-ubos.json \
  examples/nodes/wordpress-local-ubos.json
	$(FEDITEST) create-constellation \
		--name 'Mastodon vs WordPress + ActivityPub plugin (local, UBOS)' \
		--node follower_node=examples/nodes/mastodon-local-ubos.json \
		--node leader_node=examples/nodes/wordpress-local-ubos.json \
		--out $@


##### Example test plans ##########

$(EX)-testplans : \
  $(EX)/testplans/webfinger-server-imp-vs-saas-any.json \
  $(EX)/testplans/webfinger-server-imp-vs-mastodon-local-ubos.json \
  $(EX)/testplans/webfinger-server-imp-vs-wordpress-local-ubos.json \
  $(EX)/testplans/fediverse-follow-saas-any-vs-saas-any.json \
  $(EX)/testplans/fediverse-follow-mastodon-local-ubos-vs-wordpress-local-ubos.json

$(EX)/testplans/webfinger-server-imp-vs-saas-any.json : \
  dirs \
  $(EX)/session-templates/webfinger-server-all.json \
  $(EX)/constellations/imp-vs-saas-any.json
	$(FEDITEST) generate-testplan \
		--name 'WebFinger server tests (any SaaS)' \
		--session-template $(EX)/session-templates/webfinger-server-all.json \
		--constellation $(EX)/constellations/imp-vs-saas-any.json \
		--out $@

$(EX)/testplans/webfinger-server-imp-vs-mastodon-local-ubos.json : \
  dirs \
  $(EX)/session-templates/webfinger-server-all.json \
  $(EX)/constellations/imp-vs-mastodon-local-ubos.json
	$(FEDITEST) generate-testplan \
		--name 'Mastodon WebFinger server tests (local, UBOS)' \
		--session-template $(EX)/session-templates/webfinger-server-all.json \
		--constellation $(EX)/constellations/imp-vs-mastodon-local-ubos.json \
		--out $@

$(EX)/testplans/webfinger-server-imp-vs-wordpress-local-ubos.json : \
  dirs \
  $(EX)/session-templates/webfinger-server-all.json \
  $(EX)/constellations/imp-vs-wordpress-local-ubos.json
	$(FEDITEST) generate-testplan \
		--name 'WordPress + ActivityPub WebFinger server tests (local, UBOS)' \
		--session-template $(EX)/session-templates/webfinger-server-all.json \
		--constellation $(EX)/constellations/imp-vs-wordpress-local-ubos.json \
		--out $@

$(EX)/testplans/fediverse-follow-saas-any-vs-saas-any.json : \
  dirs \
  $(EX)/session-templates/fediverse-follow.json \
  $(EX)/constellations/saas-any-vs-saas-any.json
	$(FEDITEST) generate-testplan \
		--name 'Manual follow (any two SaaS)' \
		--session-template $(EX)/session-templates/fediverse-follow.json \
		--constellation $(EX)/constellations/saas-any-vs-saas-any.json \
		--out $@

$(EX)/testplans/fediverse-follow-mastodon-local-ubos-vs-wordpress-local-ubos.json : \
  dirs \
  $(EX)/session-templates/fediverse-follow.json \
  $(EX)/constellations/mastodon-local-ubos-vs-wordpress-local-ubos.json
	$(FEDITEST) generate-testplan \
		--name 'Manual follow Mastodon vs WordPress + ActivityPub (local, UBOS)' \
		--session-template $(EX)/session-templates/fediverse-follow.json \
		--constellation $(EX)/constellations/saas-any-vs-saas-any.json \
		--out $@


########## and the rest ##########

dirs :
	[[ -d $(EX)/session-templates ]] || mkdir -p $(EX)/session-templates
	[[ -d $(EX)/constellations ]] || mkdir -p $(EX)/constellations
	[[ -d $(EX)/testplans ]] || mkdir -p $(EX)/testplans

clean : clean-examples

clean-examples:
	rm $(EX)/{session-templates,constellations,testplans}/*.json >/dev/null 2>&1 || true

.PHONY: \
  default all dirs clean clean-examples \
  $(EX) $(EX)-session-templates $(EX)-constellations $(EX)-testplans

